{% set name = "pyfmmlib" %}
{% set version = "2026.1" %}
{% set sha256 = "3cbef7e859bf474ca72a96c8775e5b7c352eca78f369713f8618c849b44c877c" %}
{% set build_number = 1 %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("fortran") }}
    - llvm-openmp   # [osx]
    - libgomp       # [linux]
    - meson-python                           # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - pkg-config                             # [build_platform != target_platform]
  host:
    - python
    - pip
    - numpy
    - mako
    - meson-python
    - ninja
    - pkg-config
    - python-build
  run:
    - python

test:
  requires:
    - pytest
    - scipy
  imports:
    - {{ name }}
  source_files:
    - test
  commands:
    - cd test && python -m pytest

about:
  home: https://github.com/inducer/pyfmmlib
  license: MIT AND BSD-3-Clause
  license_file: README.rst
  summary: Python wrappers for FMMLIB2D and FMMLIB3D
  dev_url: https://github.com/inducer/pyfmmlib

extra:
  recipe-maintainers:
    - inducer
    - isuruf
    - matthiasdiener
